name: combine
"on":
  workflow_dispatch:
  pull_request:
jobs:
  combine-prs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Combine Dependabot PRs
        uses: mAAdhaTTah/combine-dependabot-prs@v1.0.5
        with:
          branchPrefix: "dependabot"
          mustBeGreen: true
          combineBranchName: "combined-prs"
          baseBranch: "main"
          openPR: true
          githubToken: ${{ secrets.GITHUB_TOKEN }}
